# =====================================================================
# Analyses on a DiffusionGenerator. Each function below is a
# self-contained problem on the generator — it takes a generator plus a
# problem spec (sets, target, observable, …) and returns the answer.
# These are the building blocks consumed by bundled analyses like
# [`ReactiveTransition`](@ref).
#
# Future extensions (spectrum, autocorrelation, semigroup propagation,
# …) plug in here without touching the discretisation or higher-level
# bundles.
# =====================================================================

# ---------------------------------------------------------------------
# A / B mask normalisation (shared by every Layer-3 analysis that takes
# subsets of the state space).
# ---------------------------------------------------------------------

# `Bool <: Integer`, so `AbstractVector{Bool}` is more specific than
# `AbstractVector{<:Integer}`; Julia's method dispatch picks the right one.
function _to_mask(spec::AbstractVector{Bool}, grid::CartesianGrid)
    N = ncells(grid)
    length(spec) == N ||
        throw(DimensionMismatch("mask length $(length(spec)) ≠ ncells = $N"))
    mask = falses(N)
    @inbounds for i in 1:N
        mask[i] = spec[i]
    end
    return mask
end

function _to_mask(spec::AbstractVector{<:Integer}, grid::CartesianGrid)
    N = ncells(grid)
    mask = falses(N)
    for i in spec
        1 <= i <= N || throw(BoundsError(1:N, i))
        mask[i] = true
    end
    return mask
end

function _to_mask(spec, grid::CartesianGrid{D}) where {D}
    N = ncells(grid)
    mask = falses(N)
    LI = LinearIndices(grid.nbox)
    @inbounds for I in CartesianIndices(grid.nbox)
        if spec(cell_center(grid, I))::Bool
            mask[LI[I]] = true
        end
    end
    return mask
end

_to_mask(spec::BitVector, grid::CartesianGrid) = begin
    N = ncells(grid)
    length(spec) == N ||
        throw(DimensionMismatch("mask length $(length(spec)) ≠ ncells = $N"))
    return copy(spec)
end

# ---------------------------------------------------------------------
# Stationary distribution: solve Qᵀ ρ = 0 with ∫ ρ dV = 1.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Invariant probability density of the discretised process generated by
`gen`: solves the discrete adjoint stationary equation `Qᵀ ρ = 0`
augmented with the normalisation `∫ ρ dV = 1`, where `Q = gen.Q` is the
rate matrix.

Returns a length-`ncells(gen)` vector with
`dot(ρ, fill(cell_volume(grid), N)) = 1`.

Throws `ArgumentError` if any axis uses absorbing boundary conditions —
the resulting chain has mass loss and admits no nontrivial normalised
invariant.

# Algorithm

`alg` is a [`StationaryAlgorithm`](@ref) (default: [`LUPinned`](@ref)).
Two families:

- [`LUPinned`](@ref): solves `Qᵀ ρ = 0` directly via a sparse linear
  solve with one row pinned to the normalisation constraint. Fast and
  exact for generators with a single near-zero eigenvalue. Breaks down
  at very small noise when the generator has multiple near-zero
  eigenvalues within machine precision (multi-basin metastability) —
  the diagnostic below catches this.
- Any [`EigensolveAlgorithm`](@ref) ([`ArnoldiSI`](@ref),
  [`ShiftInvertPower`](@ref), `KrylovKitArnoldi`): solves the same
  equation as a shifted principal-eigenpair problem at `σ = 0`.

Every algorithm struct carries its own LinearSolve.jl `linsolve` and
`linsolve_kwargs` for the inner solve — pass `KrylovJL_GMRES()` etc.
and tolerance kwargs through there:

```julia
using LinearSolve
alg = LUPinned(; linsolve = KrylovJL_GMRES(),
                 linsolve_kwargs = (; abstol = 1e-14, reltol = 1e-14))
stationary_distribution(gen, alg)
```

# Diagnostic

When `check = true` (default), the result is validated post-hoc:

  1. **Sign check**: counts entries with `ρ[i] < -eps · maximum(abs, ρ)`.
  2. **Residual check**: `‖Qᵀ ρ‖ / ‖ρ‖` should be near machine ε.
  3. **Multi-modality probe** (LU pin only): re-pins at several
     spread-out cells and checks the answer is invariant. A `max rel
     difference > multimodal_tol` reveals ≥ 2 near-zero eigenvalues
     within machine precision, in which case the returned vector is
     one quasi-stationary mode rather than the global invariant.

A single combined warning is emitted with concrete suggestions if any
check fires. Pass `check = false` to silence.
"""
function stationary_distribution(gen::DiffusionGenerator,
        alg::StationaryAlgorithm = LUPinned();
        check::Bool = true, multimodal_tol::Real = 1.0e-3,
    )::Vector{Float64}
    any(b -> b isa Absorbing, gen.bc) && throw(
        ArgumentError(
            "stationary_distribution is undefined for absorbing boundary " *
                "conditions: the chain leaks probability through the boundary " *
                "and has no nontrivial normalised invariant.",
        ),
    )
    weights = fill(cell_volume(gen.grid), ncells(gen))
    ρ = _solve_stationary(gen.Q, weights, alg)
    check && _stationary_diagnostics(gen.Q, weights, ρ, alg, multimodal_tol)
    return ρ
end

# --- Dispatch on the algorithm struct --------------------------------

function _solve_stationary(Q::SparseMatrixCSC, weights::Vector{Float64},
        alg::LUPinned)
    return _invariant_density(Q, weights;
        alg = alg.linsolve, linsolve_kwargs = alg.linsolve_kwargs,
        pin_row = alg.pin_row)
end

function _solve_stationary(Q::SparseMatrixCSC, weights::Vector{Float64},
        alg::EigensolveAlgorithm)
    # Principal eigenpair of Qᵀ at σ = 0: eigenvalue ≈ 0, eigenvector
    # is the invariant density (up to sign / normalisation).
    λ, v, _info = principal_eigenpair(transpose(Q), alg; σ = 0.0)
    s = sign(sum(v))
    s == 0 && (s = 1)
    @. v = s * v
    clamp!(v, 0.0, Inf)
    tot = dot(v, weights)
    tot > 0 && (@. v = v / tot)
    return v
end

# Post-solve diagnostic. Single combined warning with concrete pointers.
function _stationary_diagnostics(Q::SparseMatrixCSC, weights::Vector{Float64},
        ρ::Vector{Float64}, alg::StationaryAlgorithm, multimodal_tol::Real)
    issues = String[]

    ρ_max = maximum(abs, ρ)
    neg_thresh = -16 * eps(Float64) * max(ρ_max, 1.0)
    n_neg = count(<(neg_thresh), ρ)
    if n_neg > 0
        push!(issues, "$n_neg entries have ρ < $(round(neg_thresh; sigdigits = 2)) (true invariant must be ≥ 0)")
    end

    res = norm(transpose(Q) * ρ) / max(norm(ρ), eps(Float64))
    if res > 1.0e-6
        push!(issues, "‖Qᵀ ρ‖ / ‖ρ‖ ≈ $(round(res; sigdigits = 3)) (expected ≲ 1e-10)")
    end

    _multimodality_probe!(issues, Q, weights, ρ, alg, multimodal_tol)

    if !isempty(issues)
        msg = "stationary_distribution: result may be unreliable\n  • " *
            join(issues, "\n  • ") *
            "\nSuggestions:\n" *
            "  - increase the diffusion strength (the spectral gap shrinks as exp(-ΔΦ / D))\n" *
            "  - try an eigensolve backend, e.g. `stationary_distribution(gen, ArnoldiSI())`\n" *
            "  - use `quasi_stationary_distribution(gen, basin)` to compute the QSD of one metastable basin\n" *
            "  - inspect the slow modes with `eigenmodes(gen, k)`"
        @warn msg
    end
    return nothing
end

# Probe re-pins at a few spread-out cells; only meaningful for the LU
# path (eigensolves have their own convergence story).
function _multimodality_probe!(issues, Q::SparseMatrixCSC,
        weights::Vector{Float64}, ρ::Vector{Float64}, alg::LUPinned,
        multimodal_tol::Real)
    N = size(Q, 1)
    probe_pins = unique!([div(N, 4), div(N, 2), div(3N, 4), N])
    filter!(p -> p != alg.pin_row, probe_pins)
    max_diff = 0.0
    for p in probe_pins
        ρ_alt = _invariant_density(Q, weights;
            alg = alg.linsolve, linsolve_kwargs = alg.linsolve_kwargs, pin_row = p)
        d = norm(ρ - ρ_alt) / max(norm(ρ), norm(ρ_alt), eps(Float64))
        d > max_diff && (max_diff = d)
    end
    if max_diff > multimodal_tol
        push!(issues,
            "stationary solution depends on the pin row " *
            "(max rel. difference $(round(max_diff; sigdigits = 3)) across pins). " *
            "The generator has ≥ 2 near-zero eigenvalues within machine precision; " *
            "the result is one quasi-stationary mode, not the global invariant.")
    end
    return nothing
end
_multimodality_probe!(issues, Q, weights, ρ, alg::EigensolveAlgorithm, tol) = nothing

# ---------------------------------------------------------------------
# Quasi-stationary distribution of a metastable basin.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Quasi-stationary distribution (QSD) of a metastable basin together with
its exit rate.

Returns `(ρ_QSD, λ_exit)` where `ρ_QSD::Vector{Float64}` is the
length-`ncells(gen)` QSD (zero on cells outside `basin`, normalised to
`∫ ρ_QSD dV = 1` on `basin`) and `λ_exit > 0` is the corresponding
exit rate. The mean lifetime in the basin, conditional on staying in
it long enough to reach quasi-equilibrium, is `1 / λ_exit`.

`basin` accepts a predicate `x -> Bool`, a `BitVector` of length
`ncells(gen)`, or a vector of linear cell indices.

# Theory

The QSD is the principal left eigenvector of the basin sub-generator
`Q_S` (the rows and columns of `Q` indexed by the basin `S`):

```math
Q_S^\\top \\rho_S = -\\lambda_{\\text{exit}}\\, \\rho_S ,\\qquad \\rho_S \\ge 0 ,\\qquad \\int \\rho_S\\, dV = 1 ,
```

with `-λ_exit` the eigenvalue of `Q_S^T` closest to zero (it is real
and strictly negative because mass leaks across the basin boundary).
Equivalently, `λ_exit` is the smallest-magnitude eigenvalue of `-Q_S`.
For a single metastable set inside an otherwise-reflecting domain, the
QSD is the long-time limit of the distribution conditioned on not yet
having left `S`, and `-D log ρ_QSD` is the **local quasipotential** of
`S` at noise strength `D`.

This routine is the standard tool for visualising the quasipotential
well of a metastable basin at small noise, where the global
[`stationary_distribution`](@ref) becomes ill-conditioned.

# Algorithm

`alg` is an [`EigensolveAlgorithm`](@ref) (default: [`ArnoldiSI`](@ref)).
LinearSolve.jl options for the inner shift-invert solve travel on the
algorithm struct:

```julia
using LinearSolve
alg = ArnoldiSI(; linsolve = KrylovJL_GMRES(),
                  linsolve_kwargs = (; abstol = 1e-14))
quasi_stationary_distribution(gen, basin, alg)
```
"""
function quasi_stationary_distribution(gen::DiffusionGenerator, basin,
        alg::EigensolveAlgorithm = ArnoldiSI())
    grid = gen.grid
    basin_mask = _to_mask(basin, grid)
    any(basin_mask) || throw(ArgumentError("basin is empty"))

    inds = findall(basin_mask)

    # Restrict Q to the basin (rows and columns). The complement is
    # treated as absorbing — mass that leaves the basin is gone, which
    # is exactly the QSD definition.
    Q_S = gen.Q[inds, inds]

    # Principal eigenpair of Q_Sᵀ near σ = 0 has λ = -λ_exit.
    λ, v, _info = principal_eigenpair(transpose(Q_S), alg; σ = 0.0)

    s = sign(sum(v))
    s == 0 && (s = 1)
    @. v = s * v
    clamp!(v, 0.0, Inf)
    cv = cell_volume(grid)
    tot = sum(v) * cv
    tot > 0 && (@. v = v / tot)

    ρ_full = zeros(Float64, ncells(grid))
    @inbounds for (k, i) in enumerate(inds)
        ρ_full[i] = v[k]
    end

    λ_exit = -real(λ)
    return ρ_full, λ_exit
end

# ---------------------------------------------------------------------
# Committors: solve Qq = 0 with Dirichlet BCs.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Forward committor `q⁺[i]`: probability that a trajectory of the process
generated by `gen` started at cell `i` reaches `B` before `A`. Solves the
homogeneous linear system `Q q⁺ = 0` with Dirichlet conditions `q⁺ = 0`
on `A` and `q⁺ = 1` on `B`.

`A` and `B` accept a predicate `x -> Bool`, a `BitVector` of length
`ncells(gen)`, or a vector of linear cell indices.

`alg = nothing` (default) uses sparse direct LU. Pass a LinearSolve.jl
algorithm (e.g. `KrylovJL_GMRES()`) to use an iterative solver.
"""
function forward_committor(
        gen::DiffusionGenerator, A, B; alg = nothing
    )::Vector{Float64}
    grid = gen.grid
    A_mask = _to_mask(A, grid)
    B_mask = _to_mask(B, grid)
    return _forward_committor(gen.Q, A_mask, B_mask; alg = alg)
end

function _forward_committor(
        Q::SparseMatrixCSC{Float64, Int}, A_mask::BitVector, B_mask::BitVector;
        alg = nothing,
    )::Vector{Float64}
    any(A_mask) || throw(ArgumentError("set A is empty"))
    any(B_mask) || throw(ArgumentError("set B is empty"))
    any(A_mask .& B_mask) && throw(ArgumentError("sets A and B overlap"))
    N = size(Q, 1)
    mask_bc = A_mask .| B_mask
    bc_values = zeros(Float64, N)
    @inbounds for n in eachindex(B_mask)
        B_mask[n] && (bc_values[n] = 1.0)
    end
    return _solve_dirichlet(Q, mask_bc, bc_values; alg = alg)
end

"""
$(TYPEDSIGNATURES)

Backward committor `q⁻[i]`: probability that a trajectory in cell `i` last
visited `A` (rather than `B`). For reversible processes `q⁻ = 1 - q⁺`.

By default `q⁻` is solved on the discrete adjoint of `gen.Q` (time-
reversal w.r.t. the invariant measure — this requires solving the
stationary distribution as well). Pass `reverse::DiffusionGenerator` to
instead solve on a separately-supplied physical reverse-drift generator;
useful as a cross-check or for non-reversible systems where the exact
reverse SDE is known.

`alg = nothing` (default) uses sparse direct LU. Pass a LinearSolve.jl
algorithm (e.g. `KrylovJL_GMRES()`) to use an iterative solver.
"""
function backward_committor(
        gen::DiffusionGenerator, A, B;
        reverse::Union{Nothing, DiffusionGenerator} = nothing, alg = nothing,
    )::Vector{Float64}
    grid = gen.grid
    A_mask = _to_mask(A, grid)
    B_mask = _to_mask(B, grid)
    if reverse === nothing
        ρ = stationary_distribution(gen, LUPinned(linsolve = alg); check = false)
        return _backward_committor_adjoint(gen.Q, ρ, A_mask, B_mask; alg = alg)
    else
        return _backward_committor_explicit(reverse.Q, A_mask, B_mask; alg = alg)
    end
end

function _backward_committor_adjoint(
        Q::SparseMatrixCSC{Float64, Int},
        ρ::Vector{Float64},
        A_mask::BitVector,
        B_mask::BitVector;
        alg = nothing,
    )::Vector{Float64}
    any(A_mask) || throw(ArgumentError("set A is empty"))
    any(B_mask) || throw(ArgumentError("set B is empty"))
    any(A_mask .& B_mask) && throw(ArgumentError("sets A and B overlap"))
    Qadj = _adjoint_generator(Q, ρ)
    return _backward_committor_explicit(Qadj, A_mask, B_mask; alg = alg)
end

function _backward_committor_explicit(
        Qrev::SparseMatrixCSC{Float64, Int}, A_mask::BitVector, B_mask::BitVector;
        alg = nothing,
    )::Vector{Float64}
    N = size(Qrev, 1)
    mask_bc = A_mask .| B_mask
    bc_values = zeros(Float64, N)
    @inbounds for n in eachindex(A_mask)
        A_mask[n] && (bc_values[n] = 1.0)
    end
    return _solve_dirichlet(Qrev, mask_bc, bc_values; alg = alg)
end

# ---------------------------------------------------------------------
# Mean first-passage time: solve Q τ = -1 with τ = 0 on the target.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Mean first-passage time `τ[i]` from cell `i` to the target set: the
expected time for a trajectory of the process generated by `gen` to first
hit `target` starting at `i`. Solves `Q τ = -1` on the free cells with
Dirichlet condition `τ = 0` on `target`.

`target` accepts a predicate, a `BitVector`, or a vector of linear cell
indices.

`alg = nothing` (default) uses sparse direct LU. Pass a LinearSolve.jl
algorithm (e.g. `KrylovJL_GMRES()`) to use an iterative solver.
"""
function mean_first_passage_time(
        gen::DiffusionGenerator, target; alg = nothing
    )::Vector{Float64}
    target_mask = _to_mask(target, gen.grid)
    any(target_mask) || throw(ArgumentError("target set is empty"))
    Q = gen.Q
    N = size(Q, 1)
    bc_values = zeros(Float64, N)
    source = fill(-1.0, N)
    return _solve_dirichlet(Q, target_mask, bc_values; source = source, alg = alg)
end

"""
$(TYPEDSIGNATURES)

Variance `Var[τ | X_0 = i] = E[τ²] − E[τ]²` of the first-passage time
to `target`, as a function of starting cell `i`.

The first moment `τ_1 = E[τ]` solves `Q τ_1 = -1` with `τ_1|_target = 0`
([`mean_first_passage_time`](@ref)); the second moment `τ_2 = E[τ²]`
solves `Q τ_2 = -2 τ_1` with `τ_2|_target = 0`. The variance follows
from `Var[τ] = τ_2 − τ_1²`.

Returns a length-`ncells(gen)` vector of variances, all `≥ 0`.

`alg = nothing` (default) uses sparse direct LU. Pass a LinearSolve.jl
algorithm to use an iterative solver.
"""
function first_passage_variance(
        gen::DiffusionGenerator, target; alg = nothing
    )::Vector{Float64}
    target_mask = _to_mask(target, gen.grid)
    any(target_mask) || throw(ArgumentError("target set is empty"))
    Q = gen.Q
    N = size(Q, 1)
    bc_values = zeros(Float64, N)

    τ_1 = _solve_dirichlet(Q, target_mask, bc_values; source = fill(-1.0, N), alg = alg)
    τ_2 = _solve_dirichlet(Q, target_mask, bc_values; source = -2 .* τ_1, alg = alg)
    return τ_2 .- τ_1 .^ 2
end
