# =====================================================================
# Analyses on a DiffusionGenerator. Each function below is a
# self-contained problem on the generator — it takes a generator plus a
# problem spec (sets, target, observable, …) and returns the answer.
# These are the building blocks consumed by bundled analyses like
# [`ReactiveTransition`](@ref).
#
# Future extensions (spectrum, autocorrelation, semigroup propagation,
# …) plug in here without touching the discretisation or higher-level
# bundles.
# =====================================================================

# ---------------------------------------------------------------------
# A / B mask normalisation (shared by every Layer-3 analysis that takes
# subsets of the state space).
# ---------------------------------------------------------------------

# `Bool <: Integer`, so `AbstractVector{Bool}` is more specific than
# `AbstractVector{<:Integer}`; Julia's method dispatch picks the right one.
function _to_mask(spec::AbstractVector{Bool}, grid::CartesianGrid)
    N = ncells(grid)
    length(spec) == N ||
        throw(DimensionMismatch("mask length $(length(spec)) ≠ ncells = $N"))
    mask = falses(N)
    @inbounds for i in 1:N
        mask[i] = spec[i]
    end
    return mask
end

function _to_mask(spec::AbstractVector{<:Integer}, grid::CartesianGrid)
    N = ncells(grid)
    mask = falses(N)
    for i in spec
        1 <= i <= N || throw(BoundsError(1:N, i))
        mask[i] = true
    end
    return mask
end

function _to_mask(spec, grid::CartesianGrid{D}) where {D}
    N = ncells(grid)
    mask = falses(N)
    LI = LinearIndices(grid.nbox)
    @inbounds for I in CartesianIndices(grid.nbox)
        if spec(cell_center(grid, I))::Bool
            mask[LI[I]] = true
        end
    end
    return mask
end

_to_mask(spec::BitVector, grid::CartesianGrid) = begin
    N = ncells(grid)
    length(spec) == N ||
        throw(DimensionMismatch("mask length $(length(spec)) ≠ ncells = $N"))
    return copy(spec)
end

# ---------------------------------------------------------------------
# Stationary distribution: solve Qᵀ ρ = 0 with ∫ ρ dV = 1.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Invariant probability density of the discretised process generated by
`gen`: solves the discrete adjoint stationary equation `Qᵀ ρ = 0`
augmented with the normalisation `∫ ρ dV = 1`, where `Q = gen.Q` is the
rate matrix.

Returns a length-`ncells(gen)` vector with
`dot(ρ, fill(cell_volume(grid), N)) = 1`.

Throws `ArgumentError` if any axis uses absorbing boundary conditions —
the resulting chain has mass loss and admits no nontrivial normalised
invariant.

# Algorithm (`alg`)

- A `LinearSolve.SciMLLinearSolveAlgorithm` — pinned linear solve with
  the given algorithm. Default is `UMFPACKFactorization()` (sparse direct
  LU). Pass e.g. `KrylovJL_GMRES()` for an iterative solver. Extra
  kwargs flow to `LinearSolve.solve`.
- [`DenseEigen()`](@ref) — `LinearAlgebra.eigen` on `Matrix(Qᵀ)`,
  picking the eigenvector at `λ ≈ 0`. Bounded by O(N²) storage.
- [`KrylovKitSolver()`](@ref) — shift-invert Arnoldi via
  `KrylovKit.eigsolve` near `σ = 0`. Use for very large sparse
  problems. Extra kwargs flow to `KrylovKit.eigsolve`; pass
  `inner_alg = …` to control the LinearSolve algorithm used for the
  inner shift-invert solve.

# Diagnostic

Pass `check = true` to validate the result post-hoc (off by default —
the multi-modality probe runs three additional full solves):

  1. Sign check: entries below `-16ε · max|ρ|` are flagged.
  2. Residual check: `‖Qᵀ ρ‖ / ‖ρ‖` should be near machine ε.
  3. Multi-modality probe (linear-solve path only): re-pins at several
     spread-out cells and checks the answer is invariant; a non-trivial
     difference reveals ≥ 2 near-zero eigenvalues within machine
     precision (multi-basin metastability), in which case the returned
     vector is one quasi-stationary mode rather than the global
     invariant.

A single combined warning is emitted with concrete suggestions if any
check fires.
"""
function stationary_distribution(gen::DiffusionGenerator,
        alg::SciMLLinearSolveAlgorithm = UMFPACKFactorization();
        check::Bool = false, multimodal_tol::Real = 1.0e-3, kwargs...,
    )::Vector{Float64}
    _check_stationary_bc(gen)
    weights = fill(cell_volume(gen.grid), ncells(gen))
    ρ = _invariant_density(gen.Q, weights, alg; kwargs...)
    check && _stationary_diagnostics(gen.Q, weights, ρ, alg, multimodal_tol)
    return ρ
end

function stationary_distribution(gen::DiffusionGenerator,
        alg::Union{DenseEigen, KrylovKitSolver};
        check::Bool = false, multimodal_tol::Real = 1.0e-3, kwargs...,
    )::Vector{Float64}
    _check_stationary_bc(gen)
    weights = fill(cell_volume(gen.grid), ncells(gen))
    λ, v = _principal_eigenpair(transpose(gen.Q), alg; σ = 0.0, kwargs...)
    _normalise_density!(v, weights)
    check && _stationary_diagnostics(gen.Q, weights, v, alg, multimodal_tol)
    return v
end

# Sign-fix to non-negative, clamp negatives to zero, normalise so
# `dot(v, weights) = 1`. Used by every eigenpair-based density routine.
function _normalise_density!(v::AbstractVector{<:Real}, weights::AbstractVector{<:Real})
    s = sign(sum(v))
    s == 0 && (s = 1)
    @. v = s * v
    clamp!(v, 0.0, Inf)
    tot = dot(v, weights)
    tot > 0 && (@. v = v / tot)
    return v
end

function _check_stationary_bc(gen::DiffusionGenerator)
    any(b -> b isa Absorbing, gen.bc) && throw(
        ArgumentError(
            "stationary_distribution is undefined for absorbing boundary " *
                "conditions: the chain leaks probability through the boundary " *
                "and has no nontrivial normalised invariant.",
        ),
    )
    return nothing
end

# Post-solve diagnostic. Single combined warning with concrete pointers.
function _stationary_diagnostics(Q::SparseMatrixCSC, weights::Vector{Float64},
        ρ::Vector{Float64}, alg, multimodal_tol::Real)
    issues = String[]

    ρ_max = maximum(abs, ρ)
    neg_thresh = -16 * eps(Float64) * max(ρ_max, 1.0)
    n_neg = count(<(neg_thresh), ρ)
    if n_neg > 0
        push!(issues, "$n_neg entries have ρ < $(round(neg_thresh; sigdigits = 2)) (true invariant must be ≥ 0)")
    end

    res = norm(transpose(Q) * ρ) / max(norm(ρ), eps(Float64))
    if res > 1.0e-6
        push!(issues, "‖Qᵀ ρ‖ / ‖ρ‖ ≈ $(round(res; sigdigits = 3)) (expected ≲ 1e-10)")
    end

    _multimodality_probe!(issues, Q, weights, ρ, alg, multimodal_tol)

    if !isempty(issues)
        msg = "stationary_distribution: result may be unreliable\n  • " *
            join(issues, "\n  • ") *
            "\nSuggestions:\n" *
            "  - increase the diffusion strength (the spectral gap shrinks as exp(-ΔΦ / D))\n" *
            "  - try `stationary_distribution(gen, KrylovKitSolver())` for an iterative cross-check\n" *
            "  - use `quasi_stationary_distribution(gen, basin)` to compute the QSD of one metastable basin\n" *
            "  - inspect the slow modes with `eigenmodes(gen, k)`"
        @warn msg
    end
    return nothing
end

# Multimodality probe — re-pins at a few spread-out cells. Only
# meaningful for the linear-solve path; eigensolve backends are no-op.
function _multimodality_probe!(issues, Q::SparseMatrixCSC,
        weights::Vector{Float64}, ρ::Vector{Float64},
        alg::SciMLLinearSolveAlgorithm, multimodal_tol::Real)
    N = size(Q, 1)
    pins = (p for p in unique!([div(N, 4), div(N, 2), div(3N, 4), N]) if p != 1)
    max_diff = 0.0
    for p in pins
        ρ_alt = _invariant_density(Q, weights, alg; pin_row = p)
        d = norm(ρ - ρ_alt) / max(norm(ρ), norm(ρ_alt), eps(Float64))
        d > max_diff && (max_diff = d)
    end
    if max_diff > multimodal_tol
        push!(issues,
            "stationary solution depends on the pin row " *
            "(max rel. difference $(round(max_diff; sigdigits = 3)) across pins). " *
            "The generator has ≥ 2 near-zero eigenvalues within machine precision; " *
            "the result is one quasi-stationary mode, not the global invariant.")
    end
    return nothing
end

# Eigensolve backends: skip the probe.
_multimodality_probe!(issues, Q, weights, ρ, ::Union{DenseEigen, KrylovKitSolver}, _tol) =
    nothing

# ---------------------------------------------------------------------
# Quasi-stationary distribution of a metastable basin.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Quasi-stationary distribution (QSD) of a metastable basin together with
its exit rate.

Returns `(ρ_QSD, λ_exit)` where `ρ_QSD::Vector{Float64}` is the
length-`ncells(gen)` QSD (zero on cells outside `basin`, normalised to
`∫ ρ_QSD dV = 1` on `basin`) and `λ_exit > 0` is the corresponding
exit rate. The mean lifetime in the basin, conditional on staying in
it long enough to reach quasi-equilibrium, is `1 / λ_exit`.

`basin` accepts a predicate `x -> Bool`, a `BitVector` of length
`ncells(gen)`, or a vector of linear cell indices.

# Theory

The QSD is the principal left eigenvector of the basin sub-generator
`Q_S` (the rows and columns of `Q` indexed by the basin `S`):

```math
Q_S^\\top \\rho_S = -\\lambda_{\\text{exit}}\\, \\rho_S ,\\qquad \\rho_S \\ge 0 ,\\qquad \\int \\rho_S\\, dV = 1 ,
```

with `-λ_exit` the eigenvalue of `Q_S^T` closest to zero (it is real
and strictly negative because mass leaks across the basin boundary).
Equivalently, `λ_exit` is the smallest-magnitude eigenvalue of `-Q_S`.
For a single metastable set inside an otherwise-reflecting domain, the
QSD is the long-time limit of the distribution conditioned on not yet
having left `S`, and `-D log ρ_QSD` is the **local quasipotential** of
`S` at noise strength `D`.

This routine is the standard tool for visualising the quasipotential
well of a metastable basin at small noise, where the global
[`stationary_distribution`](@ref) becomes ill-conditioned.

# Algorithm (`alg`)

- [`KrylovKitSolver()`](@ref) (default) — shift-invert Arnoldi via
  `KrylovKit.eigsolve`. Kwargs flow to `KrylovKit.eigsolve`; pass
  `inner_alg = …` to control the LinearSolve algorithm used for the
  inner shift-invert solve.
- [`DenseEigen()`](@ref) — `LinearAlgebra.eigen` on `Matrix(Q_Sᵀ)`. Use
  on small basins where the dense factorisation fits in memory.

Passing a `LinearSolve.SciMLLinearSolveAlgorithm` is rejected: the QSD
eigenvalue `−λ_exit` is unknown a priori, so a single linear solve is
insufficient.
"""
function quasi_stationary_distribution(gen::DiffusionGenerator, basin,
        alg::Union{DenseEigen, KrylovKitSolver} = KrylovKitSolver(); kwargs...)
    grid = gen.grid
    basin_mask = _to_mask(basin, grid)
    any(basin_mask) || throw(ArgumentError("basin is empty"))

    inds = findall(basin_mask)

    # Restrict Q to the basin (rows and columns). The complement is
    # treated as absorbing — mass that leaves the basin is gone, which
    # is exactly the QSD definition.
    Q_S = gen.Q[inds, inds]

    # Principal eigenpair of Q_Sᵀ near σ = 0 has λ = -λ_exit.
    λ, v = _principal_eigenpair(transpose(Q_S), alg; σ = 0.0, kwargs...)
    _normalise_density!(v, fill(cell_volume(grid), length(v)))

    ρ_full = zeros(Float64, ncells(grid))
    @inbounds for (k, i) in enumerate(inds)
        ρ_full[i] = v[k]
    end

    λ_exit = -real(λ)
    return ρ_full, λ_exit
end

function quasi_stationary_distribution(::DiffusionGenerator, _basin,
        ::SciMLLinearSolveAlgorithm; kwargs...)
    throw(ArgumentError(
        "quasi_stationary_distribution: a `SciMLLinearSolveAlgorithm` is not " *
            "a valid backend because the QSD eigenvalue is unknown a priori. " *
            "Use `KrylovKitSolver()` (default) or `DenseEigen()`."
    ))
end

# ---------------------------------------------------------------------
# Committors: solve Qq = 0 with Dirichlet BCs.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Forward committor `q⁺[i]`: probability that a trajectory of the process
generated by `gen` started at cell `i` reaches `B` before `A`. Solves the
homogeneous linear system `Q q⁺ = 0` with Dirichlet conditions `q⁺ = 0`
on `A` and `q⁺ = 1` on `B`.

`A` and `B` accept a predicate `x -> Bool`, a `BitVector` of length
`ncells(gen)`, or a vector of linear cell indices.

Default `alg` is `UMFPACKFactorization()` (sparse direct LU). Pass any
`SciMLLinearSolveAlgorithm` (e.g. `KrylovJL_GMRES()`) for an iterative
solver; further kwargs flow to `LinearSolve.solve`.
"""
function forward_committor(gen::DiffusionGenerator, A, B,
        alg::SciMLLinearSolveAlgorithm = UMFPACKFactorization();
        kwargs...)::Vector{Float64}
    A_mask, B_mask = _committor_masks(gen.grid, A, B)
    return _forward_committor(gen.Q, A_mask, B_mask, alg; kwargs...)
end

function _committor_masks(grid, A, B)
    A_mask = _to_mask(A, grid)
    B_mask = _to_mask(B, grid)
    any(A_mask) || throw(ArgumentError("set A is empty"))
    any(B_mask) || throw(ArgumentError("set B is empty"))
    any(A_mask .& B_mask) && throw(ArgumentError("sets A and B overlap"))
    return A_mask, B_mask
end

function _forward_committor_system(Q::SparseMatrixCSC{Float64, Int},
        A_mask::BitVector, B_mask::BitVector)
    N = size(Q, 1)
    mask_bc = A_mask .| B_mask
    bc_values = zeros(Float64, N)
    @inbounds for n in eachindex(B_mask)
        B_mask[n] && (bc_values[n] = 1.0)
    end
    return mask_bc, bc_values
end

"""
$(TYPEDSIGNATURES)

Backward committor `q⁻[i]`: probability that a trajectory in cell `i` last
visited `A` (rather than `B`). For reversible processes `q⁻ = 1 - q⁺`.

By default `q⁻` is solved on the discrete adjoint of `gen.Q` (time-
reversal w.r.t. the invariant measure — this requires solving the
stationary distribution as well). Pass `reverse::DiffusionGenerator` to
instead solve on a separately-supplied physical reverse-drift generator;
useful as a cross-check or for non-reversible systems where the exact
reverse SDE is known.

Default `alg` is `UMFPACKFactorization()` (sparse direct LU). Pass any
`SciMLLinearSolveAlgorithm` for an iterative solver; further kwargs
flow to `LinearSolve.solve`.
"""
function backward_committor(gen::DiffusionGenerator, A, B,
        alg::SciMLLinearSolveAlgorithm = UMFPACKFactorization();
        reverse::Union{Nothing, DiffusionGenerator} = nothing, kwargs...,
    )::Vector{Float64}
    A_mask, B_mask = _committor_masks(gen.grid, A, B)
    if reverse === nothing
        ρ = stationary_distribution(gen, alg; check = false, kwargs...)
        return _backward_committor_adjoint(gen.Q, ρ, A_mask, B_mask, alg; kwargs...)
    else
        return _backward_committor_explicit(reverse.Q, A_mask, B_mask, alg; kwargs...)
    end
end

function _backward_committor_system(Qrev::SparseMatrixCSC{Float64, Int},
        A_mask::BitVector, B_mask::BitVector)
    N = size(Qrev, 1)
    mask_bc = A_mask .| B_mask
    bc_values = zeros(Float64, N)
    @inbounds for n in eachindex(A_mask)
        A_mask[n] && (bc_values[n] = 1.0)
    end
    return mask_bc, bc_values
end

function _forward_committor(Q::SparseMatrixCSC{Float64, Int},
        A_mask::BitVector, B_mask::BitVector,
        alg::SciMLLinearSolveAlgorithm = UMFPACKFactorization(); kwargs...)
    mask_bc, bc_values = _forward_committor_system(Q, A_mask, B_mask)
    return _solve_dirichlet(Q, mask_bc, bc_values, alg; kwargs...)
end

function _backward_committor_adjoint(Q::SparseMatrixCSC{Float64, Int},
        ρ::Vector{Float64}, A_mask::BitVector, B_mask::BitVector,
        alg::SciMLLinearSolveAlgorithm = UMFPACKFactorization(); kwargs...)
    Qadj = _adjoint_generator(Q, ρ)
    return _backward_committor_explicit(Qadj, A_mask, B_mask, alg; kwargs...)
end

function _backward_committor_explicit(Qrev::SparseMatrixCSC{Float64, Int},
        A_mask::BitVector, B_mask::BitVector,
        alg::SciMLLinearSolveAlgorithm = UMFPACKFactorization(); kwargs...)
    mask_bc, bc_values = _backward_committor_system(Qrev, A_mask, B_mask)
    return _solve_dirichlet(Qrev, mask_bc, bc_values, alg; kwargs...)
end

# ---------------------------------------------------------------------
# Mean first-passage time: solve Q τ = -1 with τ = 0 on the target.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Mean first-passage time `τ[i]` from cell `i` to the target set: the
expected time for a trajectory of the process generated by `gen` to first
hit `target` starting at `i`. Solves `Q τ = -1` on the free cells with
Dirichlet condition `τ = 0` on `target`.

`target` accepts a predicate, a `BitVector`, or a vector of linear cell
indices.

Default `alg` is `UMFPACKFactorization()` (sparse direct LU). Pass any
`SciMLLinearSolveAlgorithm` for an iterative solver.
"""
function mean_first_passage_time(gen::DiffusionGenerator, target,
        alg::SciMLLinearSolveAlgorithm = UMFPACKFactorization();
        kwargs...)::Vector{Float64}
    target_mask, bc_values, source = _mfpt_system(gen, target)
    return _solve_dirichlet(gen.Q, target_mask, bc_values, alg;
        source = source, kwargs...)
end

function _mfpt_system(gen::DiffusionGenerator, target)
    target_mask = _to_mask(target, gen.grid)
    any(target_mask) || throw(ArgumentError("target set is empty"))
    N = size(gen.Q, 1)
    return target_mask, zeros(Float64, N), fill(-1.0, N)
end

"""
$(TYPEDSIGNATURES)

Variance `Var[τ | X_0 = i] = E[τ²] − E[τ]²` of the first-passage time
to `target`, as a function of starting cell `i`.

The first moment `τ_1 = E[τ]` solves `Q τ_1 = -1` with `τ_1|_target = 0`
([`mean_first_passage_time`](@ref)); the second moment `τ_2 = E[τ²]`
solves `Q τ_2 = -2 τ_1` with `τ_2|_target = 0`. The variance follows
from `Var[τ] = τ_2 − τ_1²`.

Returns a length-`ncells(gen)` vector of variances, all `≥ 0`.

Default `alg` is `UMFPACKFactorization()` (sparse direct LU). Pass any
`SciMLLinearSolveAlgorithm` for an iterative solver.
"""
function first_passage_variance(gen::DiffusionGenerator, target,
        alg::SciMLLinearSolveAlgorithm = UMFPACKFactorization();
        kwargs...)::Vector{Float64}
    target_mask, bc_values, source = _mfpt_system(gen, target)
    τ_1 = _solve_dirichlet(gen.Q, target_mask, bc_values, alg;
        source = source, kwargs...)
    τ_2 = _solve_dirichlet(gen.Q, target_mask, bc_values, alg;
        source = -2 .* τ_1, kwargs...)
    return τ_2 .- τ_1 .^ 2
end
