# Set masks shared by committors, MFPTs, QSDs, and TPT bundles.
function _to_mask(spec::AbstractVector{Bool}, grid::CartesianGrid)
    N = ncells(grid)
    length(spec) == N ||
        throw(DimensionMismatch("mask length $(length(spec)) ≠ ncells = $N"))
    mask = falses(N)
    @inbounds for i in 1:N
        mask[i] = spec[i]
    end
    return mask
end

function _to_mask(spec::AbstractVector{<:Integer}, grid::CartesianGrid)
    N = ncells(grid)
    mask = falses(N)
    for i in spec
        1 <= i <= N || throw(BoundsError(1:N, i))
        mask[i] = true
    end
    return mask
end

function _to_mask(spec::Function, grid::CartesianGrid{D}) where {D}
    N = ncells(grid)
    mask = falses(N)
    LI = LinearIndices(grid.nbox)
    @inbounds for I in CartesianIndices(grid.nbox)
        if spec(cell_center(grid, I))::Bool
            mask[LI[I]] = true
        end
    end
    return mask
end

function _to_mask(spec, ::CartesianGrid)
    throw(
        ArgumentError(
            "set specification must be a predicate, BitVector, or integer cell indices; " *
                "got $(typeof(spec))",
        )
    )
end

_to_mask(spec::BitVector, grid::CartesianGrid) = begin
    N = ncells(grid)
    length(spec) == N ||
        throw(DimensionMismatch("mask length $(length(spec)) ≠ ncells = $N"))
    return copy(spec)
end

"""
$(TYPEDSIGNATURES)

Invariant probability density of the discretised process generated by
`generator`: solves the discrete adjoint stationary equation `Qᵀ ρ = 0`
augmented with the normalisation `∫ ρ dV = 1`, where `Q = generator.Q` is the
rate matrix.

Returns a length-`ncells(generator)` vector.

# Algorithm (`alg`)

- A `LinearSolve.SciMLLinearSolveAlgorithm` — pinned linear solve with
  the given algorithm. Default is `UMFPACKFactorization()` (sparse direct
  LU). Pass e.g. `KrylovJL_GMRES()` for an iterative solver. Extra
  kwargs flow to `LinearSolve.solve`.
- [`DenseEigen()`](@ref) — `LinearAlgebra.eigen` on `Matrix(Qᵀ)`,
  picking the eigenvector at `λ ≈ 0`. Bounded by O(N²) storage.
- [`KrylovKitSolver()`](@ref) — shift-invert Arnoldi via
  `KrylovKit.eigsolve` near `σ = 0`. Use for large sparse problems; pass
  `inner_alg = …` to control the LinearSolve algorithm used for the inner
  shift-invert solve. Extra kwargs flow to `KrylovKit.eigsolve`.

# Diagnostic

The result is always validated post-hoc:

  1. Sign check: entries below `-16ε · max|ρ|` are flagged.
  2. Residual check: `‖Qᵀ ρ‖ / ‖ρ‖` should be near machine ε.

Pass `verbose = true` to additionally run the multi-modality probe:

  - Linear-solve path: re-pins at several spread-out cells and checks
    the answer is invariant. Adds three full LU solves.
  - Eigensolver path (`DenseEigen`, `KrylovKitSolver`): inspects the
    spectral gap above the kernel by computing `λ₂, λ₃` of `Qᵀ` and
    flagging `|λ₂| / |λ₃| < multimodal_tol`. Adds one extra `eigenmodes`
    call (a single LU factorisation reused across Arnoldi iterations).

In both cases a positive result reveals ≥ 2 near-zero eigenvalues
within machine precision (multi-basin metastability): the returned
vector is one quasi-stationary mode rather than the global invariant,
and you should switch to [`quasi_stationary_distribution`](@ref) per
basin. The probe is off by default.

A single combined warning is emitted with concrete suggestions if any
check fires.
"""
function stationary_distribution(
        generator::DiffusionGenerator,
        alg = UMFPACKFactorization();
        verbose::Bool = false, multimodal_tol::Real = 1.0e-3, kwargs...,
    )::Vector{Float64}
    _check_stationary_bc(generator)
    weights = fill(cell_volume(generator.grid), ncells(generator))
    ρ = _invariant_density(generator.Q, weights, alg; clamp_negative = false, kwargs...)
    _stationary_diagnostics(generator.Q, weights, ρ, alg, multimodal_tol, verbose)
    _normalise_density!(ρ, weights)
    return ρ
end

function stationary_distribution(
        generator::DiffusionGenerator,
        alg::Union{DenseEigen, KrylovKitSolver};
        verbose::Bool = false, multimodal_tol::Real = 1.0e-3, kwargs...,
    )::Vector{Float64}
    _check_stationary_bc(generator)
    weights = fill(cell_volume(generator.grid), ncells(generator))
    λ, v = _principal_eigenpair(transpose(generator.Q), alg; σ = 0.0, kwargs...)
    _normalise_density!(v, weights)
    _stationary_diagnostics(generator.Q, weights, v, alg, multimodal_tol, verbose)
    return v
end

# Flip sign if needed, clamp small negatives, and normalise `dot(v, weights)`.
function _normalise_density!(v::AbstractVector{<:Real}, weights::AbstractVector{<:Real})
    s = sign(sum(v))
    s == 0 && (s = 1)
    @. v = s * v
    clamp!(v, 0.0, Inf)
    tot = dot(v, weights)
    tot > 0 && (@. v = v / tot)
    return v
end

function _check_stationary_bc(generator::DiffusionGenerator)
    any(b -> b isa Absorbing, generator.bc) && throw(
        ArgumentError(
            "stationary_distribution is undefined for absorbing boundary " *
                "conditions: the chain leaks probability through the boundary " *
                "and has no nontrivial normalised invariant.",
        ),
    )
    return nothing
end

function _stationary_diagnostics(
        Q::SparseMatrixCSC, weights::Vector{Float64},
        ρ::Vector{Float64}, alg, multimodal_tol::Real, verbose::Bool
    )
    issues = String[]

    ρ_max = maximum(abs, ρ)
    neg_thresh = -16 * eps(Float64) * max(ρ_max, 1.0)
    n_neg = count(<(neg_thresh), ρ)
    if n_neg > 0
        push!(issues, "$n_neg entries have ρ < $(round(neg_thresh; sigdigits = 2)) (true invariant must be ≥ 0)")
    end

    res = norm(transpose(Q) * ρ) / max(norm(ρ), eps(Float64))
    if res > 1.0e-6
        push!(issues, "‖Qᵀ ρ‖ / ‖ρ‖ ≈ $(round(res; sigdigits = 3)) (expected ≲ 1e-10)")
    end

    verbose && _multimodality_probe!(issues, Q, weights, ρ, alg, multimodal_tol)

    if !isempty(issues)
        msg = "stationary_distribution: result may be unreliable\n  • " *
            join(issues, "\n  • ") *
            "\nSuggestions:\n" *
            "  - increase the diffusion strength (the spectral gap shrinks as exp(-ΔΦ / D))\n" *
            "  - try `stationary_distribution(generator, KrylovKitSolver())` for an iterative cross-check\n" *
            "  - use `quasi_stationary_distribution(generator, basin)` to compute the QSD of one metastable basin\n" *
            "  - inspect the slow modes with `eigenmodes(generator, k)`"
        @warn msg
    end
    return nothing
end

# Re-pin at a few spread-out cells to reveal numerically disconnected modes.
function _multimodality_probe!(
        issues, Q::SparseMatrixCSC,
        weights::Vector{Float64}, ρ::Vector{Float64},
        alg, multimodal_tol::Real
    )
    N = size(Q, 1)
    pins = (p for p in unique!([div(N, 4), div(N, 2), div(3N, 4), N]) if p != 1)
    max_diff = 0.0
    for p in pins
        ρ_alt = _invariant_density(Q, weights, alg; pin_row = p, clamp_negative = false)
        d = norm(ρ - ρ_alt) / max(norm(ρ), norm(ρ_alt), eps(Float64))
        d > max_diff && (max_diff = d)
    end
    if max_diff > multimodal_tol
        push!(
            issues,
            "stationary solution depends on the pin row " *
                "(max rel. difference $(round(max_diff; sigdigits = 3)) across pins). " *
                "The generator has ≥ 2 near-zero eigenvalues within machine precision; " *
                "the result is one quasi-stationary mode, not the global invariant."
        )
    end
    return nothing
end

# Eigensolver path: inspect the spectral gap above the kernel.
# If |λ₂| is comparable to |λ₁| ≈ 0 (much smaller than |λ₃|), the
# generator has a numerically degenerate kernel and the returned
# vector is one direction in it (a QSD), not the global invariant.
function _multimodality_probe!(
        issues, Q::SparseMatrixCSC,
        weights::Vector{Float64}, ρ::Vector{Float64},
        alg::Union{DenseEigen, KrylovKitSolver}, multimodal_tol::Real
    )
    λs = try
        first(_eigenmodes(Q, 3, alg))
    catch err
        @debug "Multimodality probe (eigensolver path) failed" exception = (err, catch_backtrace())
        return nothing
    end
    length(λs) >= 3 || return nothing

    a2 = abs(λs[2])
    a3 = abs(λs[3])
    a3 > 0 || return nothing
    ratio = a2 / a3

    if ratio < multimodal_tol
        push!(
            issues,
            "|λ₂| / |λ₃| ≈ $(round(ratio; sigdigits = 3)) " *
                "(λ₂ ≈ $(round(λs[2]; sigdigits = 3)), λ₃ ≈ $(round(λs[3]; sigdigits = 3))). " *
                "The generator has ≥ 2 near-zero eigenvalues within machine precision; " *
                "the result is one quasi-stationary mode, not the global invariant."
        )
    end
    return nothing
end

"""
$(TYPEDSIGNATURES)

Quasi-stationary distribution (QSD) of a metastable basin.

Returns `(ρ_QSD, λ_exit)` where `ρ_QSD::Vector{Float64}` is the
length-`ncells(gen)` QSD (zero on cells outside `basin`, normalised to
`∫ ρ_QSD dV = 1` on `basin`) and `λ_exit > 0` is the corresponding
exit rate. The mean lifetime in the basin, conditional on staying in
it long enough to reach quasi-equilibrium, is `1 / λ_exit`.

`basin` accepts a predicate `x -> Bool`, a `BitVector` of length
`ncells(gen)`, or a vector of linear cell indices.

# Theory

The QSD is the principal left eigenvector of the basin sub-generator
`Q_S` (the rows and columns of `Q` indexed by the basin `S`):

```math
Q_S^\\top \\rho_S = -\\lambda_{\\text{exit}}\\, \\rho_S ,\\qquad \\rho_S \\ge 0 ,\\qquad \\int \\rho_S\\, dV = 1 ,
```

with `-λ_exit` the eigenvalue of `Q_S^T` closest to zero (it is real
and strictly negative because mass leaks across the basin boundary).
Equivalently, `λ_exit` is the smallest-magnitude eigenvalue of `-Q_S`.
For a single metastable set inside an otherwise-reflecting domain, the
QSD is the long-time limit of the distribution conditioned on not yet
having left `S`, and `-D log ρ_QSD` is the **local quasipotential** of
`S` at noise strength `D` << 1.

This routine is the standard tool for visualising the quasipotential
well of a metastable basin at small noise, where the global
[`stationary_distribution`](@ref) becomes ill-conditioned.

# Algorithm (`alg`)

- [`KrylovKitSolver()`](@ref) (default) — shift-invert Arnoldi via
  `KrylovKit.eigsolve`. Kwargs flow to `KrylovKit.eigsolve`; pass
  `inner_alg = …` to control the LinearSolve algorithm used for the
  inner shift-invert solve.
- [`DenseEigen()`](@ref) — `LinearAlgebra.eigen` on `Matrix(Q_Sᵀ)`. Use
  on small basins where the dense factorisation fits in memory.

Passing a `LinearSolve.SciMLLinearSolveAlgorithm` is rejected: the QSD
eigenvalue `−λ_exit` is unknown a priori, so a single linear solve is
insufficient.
"""
function quasi_stationary_distribution(
        generator::DiffusionGenerator, basin,
        alg::Union{DenseEigen, KrylovKitSolver} = KrylovKitSolver(); kwargs...
    )
    grid = generator.grid
    basin_mask = _to_mask(basin, grid)
    any(basin_mask) || throw(ArgumentError("basin is empty"))

    inds = findall(basin_mask)

    # Restricting to basin rows/cols treats exits as absorbing.
    Q_S = generator.Q[inds, inds]

    λ, v = _principal_eigenpair(transpose(Q_S), alg; σ = 0.0, kwargs...)
    _normalise_density!(v, fill(cell_volume(grid), length(v)))

    ρ_full = zeros(Float64, ncells(grid))
    @inbounds for (k, i) in enumerate(inds)
        ρ_full[i] = v[k]
    end

    λ_exit = -real(λ)
    return ρ_full, λ_exit
end

function quasi_stationary_distribution(
        ::DiffusionGenerator, _basin,
        alg; kwargs...
    )
    throw(
        ArgumentError(
            "quasi_stationary_distribution: a `SciMLLinearSolveAlgorithm` is not " *
                "a valid backend because the QSD eigenvalue is unknown a priori. " *
                "Use `KrylovKitSolver()` (default) or `DenseEigen()`."
        )
    )
end

# ---------------------------------------------------------------------
# Mean first-passage time: solve Q τ = -1 with τ = 0 on the target.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Mean first-passage time `τ[i]` from cell `i` to the target set: the
expected time for a trajectory of the process generated by `generator` to first
hit `target` starting at `i`. Solves `Q τ = -1` on the free cells with
Dirichlet condition `τ = 0` on `target`.

`target` accepts a predicate, a `BitVector`, or a vector of linear cell
indices.

Default `alg` is `UMFPACKFactorization()` (sparse direct LU). Pass any
`SciMLLinearSolveAlgorithm` for an iterative solver.

See also [`first_passage_variance`](@ref) and [`forward_committor`](@ref).
"""
function mean_first_passage_time(
        generator::DiffusionGenerator, target;
        alg = UMFPACKFactorization(),
        kwargs...
    )::Vector{Float64}
    target_mask, bc_values, source = _mfpt_system(generator, target)
    return _solve_dirichlet(
        generator.Q, target_mask, bc_values, alg;
        source = source, kwargs...
    )
end


function _mfpt_system(generator::DiffusionGenerator, target)
    target_mask = _to_mask(target, generator.grid)
    any(target_mask) || throw(ArgumentError("target set is empty"))
    N = size(generator.Q, 1)
    return target_mask, zeros(Float64, N), fill(-1.0, N)
end

"""
$(TYPEDSIGNATURES)

Variance `Var[τ | X_0 = i] = E[τ²] − E[τ]²` of the first-passage time
to `target`, as a function of starting cell `i`.

The first moment `τ_1 = E[τ]` solves `Q τ_1 = -1` with `τ_1|_target = 0`
([`mean_first_passage_time`](@ref)); the second moment `τ_2 = E[τ²]`
solves `Q τ_2 = -2 τ_1` with `τ_2|_target = 0`. The variance follows
from `Var[τ] = τ_2 − τ_1²`.

Returns a length-`ncells(generator)` vector of variances, all `≥ 0`.

Default `alg` is `UMFPACKFactorization()` (sparse direct LU). Pass any
`SciMLLinearSolveAlgorithm` for an iterative solver.

See also [`mean_first_passage_time`](@ref).
"""
function first_passage_variance(
        generator::DiffusionGenerator, target;
        alg = UMFPACKFactorization(),
        kwargs...
    )::Vector{Float64}
    target_mask, bc_values, source = _mfpt_system(generator, target)
    τ_1 = _solve_dirichlet(
        generator.Q, target_mask, bc_values, alg;
        source = source, kwargs...
    )
    τ_2 = _solve_dirichlet(
        generator.Q, target_mask, bc_values, alg;
        source = -2 .* τ_1, kwargs...
    )
    return τ_2 .- τ_1 .^ 2
end
