"""
$(TYPEDSIGNATURES)

Forward committor `q⁺[i]`: probability that a trajectory of the process
generated by `generator` started at cell `i` reaches `B` before `A`. Solves the
homogeneous linear system `Q q⁺ = 0` with Dirichlet conditions `q⁺ = 0`
on `A` and `q⁺ = 1` on `B`.

`A` and `B` accept a predicate `x -> Bool`, a `BitVector` of length
`ncells(generator)`, or a vector of linear cell indices.

Default `alg` is `UMFPACKFactorization()` (sparse direct LU). Pass any
`SciMLLinearSolveAlgorithm` (e.g. `KrylovJL_GMRES()`) for an iterative
solver; further kwargs flow to `LinearSolve.solve`.

See also [`backward_committor`](@ref) and [`ReactiveTransition`](@ref).
"""
function forward_committor(
        generator::DiffusionGenerator{D, BC, T}, A, B;
        alg = UMFPACKFactorization(), kwargs...
    )::Vector{T} where {D, BC, T}
    A_mask, B_mask = _committor_masks(generator.grid, A, B)
    return _forward_committor(generator.Q, A_mask, B_mask, alg; kwargs...)
end

function _committor_masks(grid, A, B)
    A_mask = _to_mask(A, grid)
    B_mask = _to_mask(B, grid)
    any(A_mask) || throw(ArgumentError("set A is empty"))
    any(B_mask) || throw(ArgumentError("set B is empty"))
    any(A_mask .& B_mask) && throw(ArgumentError("sets A and B overlap"))
    return A_mask, B_mask
end

function _forward_committor_system(
        Q::SparseMatrixCSC{T, Int},
        A_mask::BitVector, B_mask::BitVector
    ) where {T <: AbstractFloat}
    N = size(Q, 1)
    mask_bc = A_mask .| B_mask
    bc_values = zeros(T, N)
    @inbounds for n in eachindex(B_mask)
        B_mask[n] && (bc_values[n] = one(T))
    end
    return mask_bc, bc_values
end

"""
$(TYPEDSIGNATURES)

Backward committor `q⁻[i]`: probability that a trajectory in cell `i` last
visited `A` (rather than `B`). For reversible processes `q⁻ = 1 - q⁺`.

By default `q⁻` is solved on the discrete adjoint of `generator.Q` (time-
reversal w.r.t. the invariant measure — this requires solving the
stationary distribution as well). Pass `reverse::DiffusionGenerator` to
instead solve on a separately-supplied physical reverse-drift generator;
useful as a cross-check or for non-reversible systems where the exact
reverse SDE is known.

Default `alg` is `UMFPACKFactorization()` (sparse direct LU). Pass any
`SciMLLinearSolveAlgorithm` for an iterative solver; further kwargs
flow to `LinearSolve.solve`.

See also [`forward_committor`](@ref), [`stationary_distribution`](@ref),
and [`ReactiveTransition`](@ref).
"""
function backward_committor(
        generator::DiffusionGenerator{D, BC, T}, A, B;
        alg = UMFPACKFactorization(),
        reverse::Union{Nothing, DiffusionGenerator} = nothing, kwargs...,
    )::Vector{T} where {D, BC, T}
    A_mask, B_mask = _committor_masks(generator.grid, A, B)
    if reverse === nothing
        ρ = stationary_distribution(generator, alg; kwargs...)
        return _backward_committor_adjoint(generator.Q, ρ, A_mask, B_mask, alg; kwargs...)
    else
        _check_reverse_generator(generator, reverse)
        return _backward_committor_explicit(reverse.Q, A_mask, B_mask, alg; kwargs...)
    end
end

function _check_reverse_generator(generator::DiffusionGenerator, reverse::DiffusionGenerator)
    reverse.grid == generator.grid ||
        throw(ArgumentError("reverse generator must be defined on the same grid as generator"))
    reverse.bc == generator.bc ||
        throw(ArgumentError("reverse generator must use the same boundary conditions as generator"))
    size(reverse.Q) == size(generator.Q) ||
        throw(ArgumentError("reverse generator must have the same matrix size as generator"))
    return nothing
end

function _backward_committor_system(
        Qrev::SparseMatrixCSC{T, Int},
        A_mask::BitVector, B_mask::BitVector
    ) where {T <: AbstractFloat}
    N = size(Qrev, 1)
    mask_bc = A_mask .| B_mask
    bc_values = zeros(T, N)
    @inbounds for n in eachindex(A_mask)
        A_mask[n] && (bc_values[n] = one(T))
    end
    return mask_bc, bc_values
end

function _forward_committor(
        Q::SparseMatrixCSC{T, Int},
        A_mask::BitVector, B_mask::BitVector,
        alg = UMFPACKFactorization(); kwargs...
    ) where {T <: AbstractFloat}
    mask_bc, bc_values = _forward_committor_system(Q, A_mask, B_mask)
    return _solve_dirichlet(Q, mask_bc, bc_values, alg; kwargs...)
end

function _backward_committor_adjoint(
        Q::SparseMatrixCSC{T, Int},
        ρ::Vector{T}, A_mask::BitVector, B_mask::BitVector,
        alg = UMFPACKFactorization(); kwargs...
    ) where {T <: AbstractFloat}
    Qadj = _adjoint_generator(Q, ρ)
    return _backward_committor_explicit(Qadj, A_mask, B_mask, alg; kwargs...)
end

function _backward_committor_explicit(
        Qrev::SparseMatrixCSC{T, Int},
        A_mask::BitVector, B_mask::BitVector,
        alg = UMFPACKFactorization(); kwargs...
    ) where {T <: AbstractFloat}
    mask_bc, bc_values = _backward_committor_system(Qrev, A_mask, B_mask)
    return _solve_dirichlet(Qrev, mask_bc, bc_values, alg; kwargs...)
end
