# =====================================================================
# Layer-3 analyses on a DiffusionGenerator. Each function below is a
# self-contained problem on the generator — it takes a generator plus a
# problem spec (sets, target, observable, …) and returns the answer.
# These are the building blocks; bundled analyses like [`TPT`](@ref)
# call into them.
#
# Future extensions (spectrum, autocorrelation, semigroup propagation,
# …) plug in here without touching TPT or the discretisation.
# =====================================================================

# ---------------------------------------------------------------------
# A / B mask normalisation (shared by every Layer-3 analysis that takes
# subsets of the state space).
# ---------------------------------------------------------------------

# `Bool <: Integer`, so `AbstractVector{Bool}` is more specific than
# `AbstractVector{<:Integer}`; Julia's method dispatch picks the right one.
function _to_mask(spec::AbstractVector{Bool}, grid::CartesianGrid)
    N = ncells(grid)
    length(spec) == N ||
        throw(DimensionMismatch("mask length $(length(spec)) ≠ ncells = $N"))
    mask = falses(N)
    @inbounds for i in 1:N
        mask[i] = spec[i]
    end
    return mask
end

function _to_mask(spec::AbstractVector{<:Integer}, grid::CartesianGrid)
    N = ncells(grid)
    mask = falses(N)
    for i in spec
        1 <= i <= N || throw(BoundsError("cell index $i out of range 1:$N"))
        mask[i] = true
    end
    return mask
end

function _to_mask(spec, grid::CartesianGrid{D}) where {D}
    N = ncells(grid)
    mask = falses(N)
    LI = LinearIndices(grid.nbox)
    @inbounds for I in CartesianIndices(grid.nbox)
        if spec(cell_center(grid, I))::Bool
            mask[LI[I]] = true
        end
    end
    return mask
end

_to_mask(spec::BitVector, grid::CartesianGrid) = begin
    N = ncells(grid)
    length(spec) == N ||
        throw(DimensionMismatch("mask length $(length(spec)) ≠ ncells = $N"))
    return copy(spec)
end

# ---------------------------------------------------------------------
# Stationary distribution: solve Qᵀ ρ = 0 with ∫ ρ dV = 1.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Invariant probability density of the discretised process generated by
`gen`: solves the discrete adjoint stationary equation `Qᵀ ρ = 0`
augmented with the normalisation `∫ ρ dV = 1`, where `Q = gen.Q` is the
rate matrix.

Returns a length-`ncells(gen)` vector with `dot(ρ, fill(cell_volume(grid), N)) = 1`.
"""
function stationary_distribution(gen::DiffusionGenerator)::Vector{Float64}
    weights = fill(cell_volume(gen.grid), ncells(gen))
    return _invariant_density(gen.Q, weights)
end

# ---------------------------------------------------------------------
# Committors: solve Qq = 0 with Dirichlet BCs.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Forward committor `q⁺[i]`: probability that a trajectory of the process
generated by `gen` started at cell `i` reaches `B` before `A`. Solves the
homogeneous linear system `Q q⁺ = 0` with Dirichlet conditions `q⁺ = 0`
on `A` and `q⁺ = 1` on `B`.

`A` and `B` accept a predicate `x -> Bool`, a `BitVector` of length
`ncells(gen)`, or a vector of linear cell indices.
"""
function forward_committor(
    gen::DiffusionGenerator, A, B
)::Vector{Float64}
    grid = gen.grid
    A_mask = _to_mask(A, grid)
    B_mask = _to_mask(B, grid)
    return _forward_committor(gen.Q, A_mask, B_mask)
end

function _forward_committor(
    Q::SparseMatrixCSC{Float64,Int}, A_mask::BitVector, B_mask::BitVector
)::Vector{Float64}
    any(A_mask) || throw(ArgumentError("set A is empty"))
    any(B_mask) || throw(ArgumentError("set B is empty"))
    any(A_mask .& B_mask) && throw(ArgumentError("sets A and B overlap"))
    N = size(Q, 1)
    mask_bc = A_mask .| B_mask
    bc_values = zeros(Float64, N)
    @inbounds for n in eachindex(B_mask)
        B_mask[n] && (bc_values[n] = 1.0)
    end
    return _solve_dirichlet(Q, mask_bc, bc_values)
end

"""
$(TYPEDSIGNATURES)

Backward committor `q⁻[i]`: probability that a trajectory in cell `i` last
visited `A` (rather than `B`). For reversible processes `q⁻ = 1 - q⁺`.

By default `q⁻` is solved on the discrete adjoint of `gen.Q` (time-
reversal w.r.t. the invariant measure — this requires solving the
stationary distribution as well). Pass `reverse::DiffusionGenerator` to
instead solve on a separately-supplied physical reverse-drift generator;
useful as a cross-check or for non-reversible systems where the exact
reverse SDE is known.
"""
function backward_committor(
    gen::DiffusionGenerator, A, B; reverse::Union{Nothing,DiffusionGenerator}=nothing
)::Vector{Float64}
    grid = gen.grid
    A_mask = _to_mask(A, grid)
    B_mask = _to_mask(B, grid)
    if reverse === nothing
        ρ = stationary_distribution(gen)
        return _backward_committor_adjoint(gen.Q, ρ, A_mask, B_mask)
    else
        return _backward_committor_explicit(reverse.Q, A_mask, B_mask)
    end
end

function _backward_committor_adjoint(
    Q::SparseMatrixCSC{Float64,Int},
    ρ::Vector{Float64},
    A_mask::BitVector,
    B_mask::BitVector,
)::Vector{Float64}
    any(A_mask) || throw(ArgumentError("set A is empty"))
    any(B_mask) || throw(ArgumentError("set B is empty"))
    any(A_mask .& B_mask) && throw(ArgumentError("sets A and B overlap"))
    Qadj = _adjoint_generator(Q, ρ)
    return _backward_committor_explicit(Qadj, A_mask, B_mask)
end

function _backward_committor_explicit(
    Qrev::SparseMatrixCSC{Float64,Int}, A_mask::BitVector, B_mask::BitVector
)::Vector{Float64}
    N = size(Qrev, 1)
    mask_bc = A_mask .| B_mask
    bc_values = zeros(Float64, N)
    @inbounds for n in eachindex(A_mask)
        A_mask[n] && (bc_values[n] = 1.0)
    end
    return _solve_dirichlet(Qrev, mask_bc, bc_values)
end

# ---------------------------------------------------------------------
# Mean first-passage time: solve Q τ = -1 with τ = 0 on the target.
# ---------------------------------------------------------------------

"""
$(TYPEDSIGNATURES)

Mean first-passage time `τ[i]` from cell `i` to the target set: the
expected time for a trajectory of the process generated by `gen` to first
hit `target` starting at `i`. Solves `Q τ = -1` on the free cells with
Dirichlet condition `τ = 0` on `target`.

`target` accepts a predicate, a `BitVector`, or a vector of linear cell
indices.
"""
function mean_first_passage_time(
    gen::DiffusionGenerator, target
)::Vector{Float64}
    target_mask = _to_mask(target, gen.grid)
    any(target_mask) || throw(ArgumentError("target set is empty"))
    Q = gen.Q
    N = size(Q, 1)
    bc_values = zeros(Float64, N)
    source = fill(-1.0, N)
    return _solve_dirichlet(Q, target_mask, bc_values; source=source)
end
